services:
  - type: web
    name: Toxic-MD
    env: docker
    plan: free
    buildCommand: "npm install"
    dockerfilePath: ./Dockerfile
    repo: https://github.com/xhclintohn/Toxic-Md
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        description: 🔐 Your bot’s session ID. Scan the QR code to get this or the bot won’t start!
      - key: PORT
        value: 3000
